### PR TITLE
Conformance clauses

### PR DESCRIPTION
**Pull request by sparrell**
Proposed conformance clauses for the concepts discussed at previous meetings. Ie to be conformant to this spec, you need to be conformant to language, to at least one transport spec, and only to approved actuator profile spec.

### CODE REVIEW

**Comment by dlemire60** [comment]
I think this approach to conformance works, and achieves the desired result.  

One uncertainty I take from this is whether implementation of a _Standard_ AP is required for conformance. 

- CC 4.9 says you have to have at least one AP, but (apparently) could be satisfied by either a Standard or a Custom AP. 
- CC 4.10 says you have to implement Standard APs in a conformant manner.
- CC 4.11 says it's permissible to extend a conformant implementation of a Standard AP

So if I have an implementation that's conformant in all other dimensions but only implements a Custom AP, is it conformant to the Architecture Spec?

Other comments:

- General editorial:  "ie" should be "i.e.,", "eg" should be "e.g.,", and always lower case
- This specification should refer to _Transfer_ Specifications; transport is Layer 4 (i.e., TCP, UDP) 
- Line 345:  suggest "corresponding" in place of "appropriate"
- Line 345:  should "MUST" be "MAY" in this clause?
- Line 355:  typo:  "malare" should be "mal_w_are"

**Comment by dlemire60** [comment]
After re-reviewing this, I have two further comments

1. Do the definitions of the various lists belongs in the conformance section, or should they be with the other terminology definitions in section 2. I understand the benefits of having the definitions close to the associated requirements but I think ultimately it's better form to keep definitions in a single place and refer back to them.

2. Currently the conformance section defines list of Transfer (AKA Transport) specs and AP specs. This seems to overlap with the [registry](https://github.com/oasis-open/openc2-custom-aps/blob/master/namespace-registry.md) in the [Custom APs Repo](https://github.com/oasis-open/openc2-custom-aps), which seems like a cleaner solution in the long run (e.g., all of the "if arch goes for approval prior" caveats wouldn't be needed).

**Comment by sparrell** [comment]
this pull request will eventually be recreated onto the new template doc, once all the previously agreed changes are into the new doc. This PR is being kept open until then so we don't lost tract of the proposed changes

**Comment by sparrell** [comment]
I am having trouble resolving the conflicts because of all the other intervening changes. So I have stored off my proposed conformance clauses, I'm going to reset my fork and get in sync with current working, and then I will reintroduce the conformance clause proposals in a new PR.

**Pull request closed without merging**
